const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const errors=[],hostResourceFailures=[];
 const page=await browser.newPage({viewport:{width:768,height:1200},deviceScaleFactor:1});
 page.on('pageerror',e=>errors.push(e.message));
 page.on('console',m=>{if(m.type()==='error'){if(m.text().startsWith('Failed to load resource:'))hostResourceFailures.push(m.location().url);else errors.push(m.text());}});
 await page.goto('file://'+process.cwd()+'/preview.html');
 const frame=page.frameLocator('iframe');
 await frame.locator('#fluidic-cfd[data-ready=true]').waitFor({timeout:60000});
 if(errors.length)console.log('Initialization errors:',errors);
 await frame.locator('canvas').first().waitFor();
 await page.screenshot({path:'../cfd-desktop.png',fullPage:true});
 const initial=await frame.locator('#cfd-output').innerText();
 await frame.locator('#cfd-case').selectOption('mix-s2');
 const changed=await frame.locator('#cfd-output').innerText();
 if(initial===changed)throw Error('Case selector did not update the computed flows');
 await frame.locator('#cfd-field').selectOption('speed');
 if(!await frame.locator('#cfd-field-label').innerText().then(x=>x.includes('mm/s')))throw Error('Field selector failed');
 await frame.locator('#cfd-vectors').check();
 await frame.locator('#cfd-slice').fill('200');
 await frame.locator('#cfd-slice').dispatchEvent('input');
 if(await frame.locator('#cfd-slice-value').innerText()!=='200 µm')throw Error('Slice control failed');
 await frame.locator('#cfd-view').selectOption('top');
 await page.screenshot({path:'../cfd-slice.png',fullPage:true});
 await page.setViewportSize({width:352,height:1200});await page.emulateMedia({colorScheme:'dark'});
 await frame.locator('#cfd-slice').fill('480');await frame.locator('#cfd-slice').dispatchEvent('input');
 await frame.locator('#cfd-view').selectOption('oblique');
 await frame.locator('summary').click();
 await page.screenshot({path:'../cfd-mobile-dark.png',fullPage:true});
 const overflow=await page.frames()[1].evaluate(()=>({body:document.body.scrollWidth,width:document.documentElement.clientWidth,webglError:!document.getElementById('cfd-webgl-error').hidden}));
 if(overflow.body>overflow.width+1)throw Error('Horizontal overflow '+JSON.stringify(overflow));
 if(overflow.webglError)throw Error('WebGL failed');
 // Standalone must work with every network request blocked.
 const offline=await browser.newPage({viewport:{width:768,height:1100}});
 offline.on('pageerror',e=>errors.push(e.message));
 await offline.route(/^https?:/,route=>route.abort());
 await offline.goto('file://'+process.cwd()+'/fluidic-matrix-multiplier-3d.html');
 await offline.locator('#fluidic-cfd[data-ready=true]').waitFor();
 if(!await offline.locator('#cfd-webgl-error').isHidden())throw Error('Offline WebGL failed');
 await offline.screenshot({path:'../cfd-offline.png',fullPage:true});
 console.log(JSON.stringify({errors,hostResourceFailures,overflow,computedFlowUpdated:true,sliceUpdated:true,offlineLoaded:true},null,2));
 await browser.close();if(errors.length)process.exitCode=1;
})();
